[package]
name = "cargo-sort-ck"
version = "2.0.0"
authors = ["Devin R <devin.ragotzy@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Check if tables and items in a .toml file are lexically sorted"
repository = "https://github.com/DevinR528/cargo-sort-ck"
keywords = ["cargo", "subcommand", "dependencies", "sort", "check"]
categories = ["development-tools::cargo-plugins", "development-tools"]
edition = "2018"
readme = "README.md"
exclude = [ "examp" ]

[dependencies]
clap = "2.33"
termcolor="1.1"
toml-parse = "0.2.7"

[dev-dependencies]
pretty_assertions="0.6"

[[bin]]
name = "cargo-sort-ck"
path = "src/main.rs"

[badges]
travis-ci = { repository = "DevinR528/cargo-sort-ck" }
