[package]
name = "cargo-sort-ck"
version = "0.3.2"
authors = ["Devin R <devin.ragotzy@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Check Cargo.toml for sorted dependencies"
repository = "https://github.com/DevinR528/cargo-expand"
keywords = ["cargo", "subcommand", "dependencies", "sort", "check"]
categories = ["development-tools::cargo-plugins", "development-tools"]
edition = "2018"
readme = "README.md"
exclude = [ "examp" ]

[dependencies]
clap = "2.33"
colored="1.8"
termcolor="1.0"

[dev-dependencies]
pretty_assertions="0.6"

[badges]
travis-ci = { repository = "DevinR528/cargo-sort-ck" }
