[dependencies]
a="0"
b="0"
c="0"
d="0"

["build-dependencies"]
w="0"
x="9"
y="3"

["build-dependencies.f"]
version="0"

["build-dependencies.a"]
version="0"

[dependencies.alpha]
version = "0.15"
default-features = false
features = ["full", "parsing", "printing", "visit-mut"]

[dependencies.beta]
version = "0.15"
default-features = false
features = ["full", "parsing", "printing", "visit-mut"]


[dependencies.syn]
version = "0.15"
default-features = false
features = ["full", "parsing", "printing", "visit-mut"]
